image: $IMAGE

stages:
    - test
    - build
    - deploy

test:
    stage: test
    before_script:
        - apt-get update -qq && apt-get install -y -qq
          gcc make cmake curl wget
          python3-all-dev python-virtualenv
          zlib1g-dev libbz2-dev liblzma-dev libncurses5-dev libcurl4-gnutls-dev
          libssl-dev libffi-dev valgrind
    script:
        - make venv
        - make -j 1 test mem_check
        - make docs

.many-linux: &many-linux-def
  image: quay.io/pypa/manylinux2010_x86_64
  stage: build
  before_script:
      - echo "Nothing to do in before_script"
  artifacts:
      paths:
          - wheelhouse/*.whl
  only:
      - tags

build:many-linux-5:
    <<: *many-linux-def
    script:
        - ./build-wheels.sh . 5

build:many-linux-6:
    <<: *many-linux-def
    script:
        - ./build-wheels.sh . 6

build:sdist:
    stage: build
    before_script:
        - apt-get update -qq && apt-get install -y -qq
          python3-all-dev python-virtualenv
    script:
        - make sdist
    artifacts:
        paths:
            - dist/*.tar.gz

deploy:pypi:
    stage: deploy
    before_script:
        - apt-get update -qq && apt-get install -y -qq
          python3-all-dev python-virtualenv
    script:
        - make build
        - source pypi_build/bin/activate
        - twine upload dist/*.tar.gz wheelhouse/*.whl
    only:
        - tags
